kind: pipeline
type: docker
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: registryuser
    password:
      from_secret: registrylogin
    repo: reg.s-c.systems/pr0/pr0music_web_backend
    tags: latest
    registry: reg.s-c.systems
